apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
  namespace: fcg

data:
  kong.yaml: |
    _format_version: "3.0"
    _transform: true

    consumers:
      - username: fcg-user
        jwt_secrets:
          - key: PedroIghor
            algorithm: HS256
            secret: EAA4Cf4JnqYwBP9MSZC8cHvMSvmShHZBU27qQxZBS3ORNSoIdEz3me0QHZABLNBiEWtDmVLZBVeMF8QZCd

    services:
      - name: users-api
        protocol: http
        host: users-api.fcg.svc.cluster.local
        port: 80
        path: /api/users
        routes:
          - name: users-api-route
            paths:
              - /users
            strip_path: true

      - name: catalog-api
        protocol: http
        host: catalog-api.fcg.svc.cluster.local
        port: 80
        routes:
          - name: catalog-api-route
            paths:
              - /catalog
            strip_path: true
            plugins:
              - name: jwt
                config:
                  key_claim_name: iss
                  claims_to_verify:
                    - exp