apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  namespace: fcg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: kong:3.9
          ports:
            - containerPort: 8000
            - containerPort: 8001
          env:
            - name: KONG_DATABASE
              value: "off"

            - name: KONG_DECLARATIVE_CONFIG
              value: "/kong/declarative/kong.yaml"

            - name: KONG_PROXY_LISTEN
              value: "0.0.0.0:8000"

            - name: KONG_ADMIN_LISTEN
              value: "0.0.0.0:8001"

          volumeMounts:
            - name: kong-config
              mountPath: /kong/declarative

      volumes:
        - name: kong-config
          configMap:
            name: kong-config